version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    executor:
      name: win/default
      # shell: powershel.exe
    working_directory:  ~/test-changes/
    environment:

    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install --no-deps -r ./requirements.txt
      - run:
          name: Install geckodriver
          command: choco install selenium-gecko-driver
      - run:
          name: Install selenium
          command: powershell $progressPreference = 'silentlyContinue' Invoke-WebRequest -Uri "https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar" -OutFile ".\\selenium-server-standalone.jar"
      - run:
          name: Install Firefox
          command: choco install firefox-nightly --pre
      - run:
          name: Run tests
          no_output_timeout: 30m
          environment:
          MOZ_HEADLESS: 1
          command: pytest test_search.py --driver Firefox --variables stage.json --ui-test-serial.html --self-contained-html
      - store_artifacts:
          path: ui-test-release.html
  test:
    working_directory:  ~/test-changes/
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: Run tests
          environment:
          MOZ_HEADLESS: 1
          command: pytest test_search.py --driver Remote --port 4444 --capability browserName firefox --variables stage.json
      - store_artifacts:
            path: ui-test-release.html
workflows:
  # version: 2.1
  build_and_test:
    jobs:
        - build
        - test:
            requires:
              - build


